fix_seed: 0
checkpoints_every: 100
tensorboard_log: True
result_path: ./results/test

resume:
  resume: False
  resume_path: testadapterh_12tuneall_sgdlr001mixlenpad_esmpool2/checkpoints/checkpoint_0040000.pth
  restart_optimizer: True

model:
  compile_model: False
  residue_out_dim: 128
  protein_out_dim: 256
  residue_num_projector: 1
  protein_num_projector: 2

  esm_encoder:
    model_name:  esm2_t30_150M_UR50D # esm2_t33_650M_UR50D, esm2_t30_150M_UR50D, esm2_t12_35M_UR50D, esm2_t6_8M_UR50D
    max_length: 512
    residue_inner_dim: 1024
    protein_inner_dim: 4096
    tune_ESM_table: False
    fine_tuning:
      enable: False
      unfix_last_layer: 6
    adapter_h:
      enable: False
      num_end_adapter_layers: 16
      module_type: "MLP1"
    lora:
      enable: False
      r: 8
      alpha: 32
      dropout: 0.05
      resume:
        enable: False
        checkpoint_path: path/to/checkpoints.pth
    pool_mode: 2 #average pooling without padding
  struct_encoder:
    residue_inner_dim: 1024
    protein_inner_dim: 4096
    use_seq:
      enable: False
      seq_embed_mode: "embedding" #"embedding","ESM2"
      seq_embed_dim: 20 #1280 for ESM2
    lora:
      enable: False
      r: 8
      alpha: 32
      dropout: 0.05
      resume:
        enable: False
        checkpoint_path: path/to/checkpoints.pth

train_settings:
  data_path: /mnt/hdd8/mehdi/datasets/gvp-splm/train/
  num_steps: 100
  shuffle: True
  mixed_precision: bf16 # no, fp16, bf16, fp8
  batch_size: 32
  residue_batch_size: 2000
  num_workers: 8
  gradient_accumulation: 1
  n_views: 2
  temperature: 0.05
  plddt_weight: False


valid_settings:
  data_path: /mnt/hdd8/mehdi/datasets/gvp-splm/valid/
  cath_path: /mnt/hdd8/mehdi/datasets/gvp-splm/Rep_subfamily_basedon_S40pdb.fa
  deaminase_path: /mnt/hdd8/mehdi/datasets/gvp-splm/Deaminases_clustering/Table_S1.xlsx
  kinase_path: /mnt/hdd8/mehdi/datasets/gvp-splm/kinase_clustering/GPS5.0_homo_hasPK_with_kinasedomain.txt
  do_every: 50 # steps
  num_workers: 8
  batch_size: 16
  eval_struct:
      enable: False
      do_every: 50
      cath_pdb_path: /mnt/hdd8/mehdi/datasets/gvp-splm/CATH_4_3_0_non-rep_gvp/

optimizer:
  name: adam
  lr_seq: 8e-5
  lr_struct: 8e-5
  weight_decouple: True
  weight_decay: 0.01
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 50
    min_lr_seq: 1e-7
    min_lr_struct: 1e-7
    gamma: 1
    first_cycle_steps: 100
